name: Push Main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  master:
    runs-on: ubuntu-22.04
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Update data
        run: |
          npm run data:update-network-info
      - name: Build
        run: npm run build ${{ secrets.CLOUDFLARE_API_TOKEN }} ${{ secrets.GH_AUTOMATION_TOKEN }}
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'demo-calculator'
          gitHubToken: ${{ secrets.GH_AUTOMATION_TOKEN }}
          branch: 'main'
          directory: './build'
          wranglerVersion: '3'

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Scheduler
          author_email: scheduler@github.io
          message: 'Update data'
