name: Push Main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  master:
    runs-on: ubuntu-22.04
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.CLOUDFLARE_API_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.GH_AUTOMATION_TOKEN}} | sed 's/./& /g'
      - name: Update data
        run: |
          npm run data:update-network-info ${{ secrets.GH_AUTOMATION_TOKEN }} dev_anhnt
      - name: Build
        run: npm run build ${{ secrets.CLOUDFLARE_API_TOKEN }} ${{ secrets.GH_AUTOMATION_TOKEN }}
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'demo-calculator'
          gitHubToken: ${{ secrets.GH_AUTOMATION_TOKEN }}
          branch: 'main'
          directory: './build'
          wranglerVersion: '3'

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Scheduler
          author_email: scheduler@github.io
          message: 'Update data'
