name: Push Main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  master:
    runs-on: ubuntu-22.04
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Cloudflare Pages
        id: cloudflare_deployment
        uses: cloudflare/pages-action@v1
        with:
          apiToken: 'Ds8b00YrNZ_wCUj-RELht_hPZazCsnWHTq-oSdN1'
          accountId: 'b367414b5bc07c5e6e07c61d633ee0af'
          projectName: 'demo-calculator'
          gitHubToken: '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'
          branch: 'main'
          workingDirectory: './'
          directory: './build'
          wranglerVersion: '3'
