name: Push Main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  master:
    runs-on: ubuntu-22.04
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: qPCIv1BC76bNcuSZqjfeAX0Rmlr3aVdWKoDY9gpG
          accountId: b367414b5bc07c5e6e07c61d633ee0af
          projectName: 'demo-calculator'
          gitHubToken: ${{ secrets.GH_AUTOMATION_TOKEN }}
          branch: 'main'
          directory: './build'
          wranglerVersion: '3'
