name: Push Main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  master:
    runs-on: ubuntu-22.04
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to Cloudflare Pages
        id: cloudflare_deployment
        uses: cloudflare/pages-action@v1
        with:
          apiToken: '33P7SkkertgE0N02wB9jt80IBq9G2Uk-2LvRkPng'
          accountId: 'b367414b5bc07c5e6e07c61d633ee0af'
          projectName: 'demo-calculator'
          gitHubToken: ${{ secrets.GH_AUTOMATION_TOKEN }}
          branch: main
          wranglerVersion: '3'
