name: Push Main
on:
  pull_request:
    branches:
      - main
      - dev
      - main_dev
  push:
    branches:
      - main
      - dev
      - main_dev

jobs:
  master:
    runs-on: ubuntu-22.04
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Build Preview
        run: |
          npm install --no-save | grep -v 'YN0013'
          if [ ${{ github.ref_name }} == 'main' ]; then
            npm run data:update-build-number
            echo "is MAIN2 branch"
          fi
          CI=false yarn build
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'demo-calculator'
          gitHubToken: ${{ secrets.GH_AUTOMATION_TOKEN }}
          branch: 'main'
          directory: './build'
          wranglerVersion: '3'

      - if: "github.ref_name == 'main' && github.event_name == 'push'"
        name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Scheduler
          author_email: scheduler@github.io
          message: 'Update data'
